### PR TITLE
Fix nil check when env not defined

### LINKED ISSUE #26: Attempt to concatenate local 'env_name' (a nil value)
My config is as suggested:
```lua
  {
    "adalessa/laravel.nvim",
    dependencies = {
      "nvim-telescope/telescope.nvim",
      -- which-key integration
      {
        "folke/which-key.nvim",
        opts = {
          defaults = {
            ["<leader>cp"] = { name = "+php" },
          },
        },
      },
    },
    cmd = { "Sail", "Artisan", "Composer", "Npm", "Yarn", "Laravel" },
    keys = {
      { "<leader>cpa", ":Laravel artisan<cr>", desc = "Artisan" },
      { "<leader>cpr", ":Laravel routes<cr>", desc = "Routes" },
      {
        "<leader>cpt",
        function()
          require("laravel").app.sendToTinker()
        end,
        mode = "v",
        desc = "Laravel Application Routes",
      },
    },
    ft = { "blade", "php" },
    config = function()
      require("laravel").setup()
      require("telescope").load_extension("laravel")
    end,
  }
```
I am getting this error message:
image

### PR DESCRIPTION
**Pull request by dorkster100**
fix #26

### CODE REVIEW

**Comment by guiwestrup** [comment]
Is there a way to use this PR in my project?

**Comment by dorkster100** [comment]
Can't you temporarily set the plugin URL to my fork?

**Comment by guiwestrup** [comment]
I tried, but i think i did it wrong:

return {
  "dorkster100/laravel.nvim",
  lazy = false,
  dependencies = {
    "nvim-telescope/telescope.nvim",
    -- which-key integration
    {
      "folke/which-key.nvim",
      opts = {
        defaults = {
          ["<leader>cp"] = { name = "+php" },
        },
      },
    },
  },
  cmd = { "Sail", "Artisan", "Composer", "Npm", "Yarn", "Laravel" },
  keys = {
    { "<leader>cpa", ":Laravel artisan<cr>", desc = "Artisan" },
    { "<leader>cpr", ":Laravel routes<cr>", desc = "Routes" },
    {
      "<leader>cpt",
      function() require("laravel").app.sendToTinker() end,
      mode = "v",
      desc = "Laravel Application Routes",
    },
  },
  ft = { "blade", "php" },
  config = function()
    require("laravel").setup()
    require("telescope").load_extension "laravel"
  end,
}

**Comment by dorkster100** [comment]
> I tried, but i think i did it wrong:
> 
> return { "dorkster100/laravel.nvim", lazy = false, dependencies = { "nvim-telescope/telescope.nvim", -- which-key integration { "folke/which-key.nvim", opts = { defaults = { ["cp"] = { name = "+php" }, }, }, }, }, cmd = { "Sail", "Artisan", "Composer", "Npm", "Yarn", "Laravel" }, keys = { { "cpa", ":Laravel artisan", desc = "Artisan" }, { "cpr", ":Laravel routes", desc = "Routes" }, { "cpt", function() require("laravel").app.sendToTinker() end, mode = "v", desc = "Laravel Application Routes", }, }, ft = { "blade", "php" }, config = function() require("laravel").setup() require("telescope").load_extension "laravel" end, }

Yes, as you can see I am merging my `upstream` branch into main here, so you would need to use that, as shown here: https://github.com/folke/lazy.nvim you need to add branch = "upstream" to your config, this should work i think.

**Pull request merged**
